name: BanTools
version: 1.0.0
api: [2.0.0, 2.1.0, 3.0.0-ALPHA3, 3.0.0-ALPHA2, 3.0.0-ALPHA4, 3.0.0-ALPHA6]
author: BEcraft Gameplay
main: Tool\Main
commands:
 invisible:
  description: "Make you a ghost"
  usage: "/invisible"
 visible:
  description: "Make you visible to players"
  usage: "/visible"
 eb:
  description: "Allows you to ban a user."
  usage: "/eb"
 ep:
  description: "Pardon any player which is banned."
  usage: "/ep"
 info:
  description: "See any players information"
  usage: "/info"
 fre:
  description: "feeze and unFreeze any player"
  usage: "/fre"
 co:
  description: "Chat just for op"
  usage: "/co"
 tools:
  description: "Check all commands"
  usage: "/tools"
 eblist:
  description: "Check all banned players from your server"
  usage: "/eblist"
 bancheck:
  description: "Check info about any banned player"
  usage: "/bancheck"
 
